# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics/metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics/metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15metrics/metrics.proto\x12\x07metrics\"\xae\x01\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x19\n\x11timestamp_unix_ms\x18\x03 \x01(\x03\x12\x10\n\x08\x61gent_id\x18\x04 \x01(\t\x12+\n\x06labels\x18\x05 \x03(\x0b\x32\x1b.metrics.Metric.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"8\n\x14SubmitMetricsRequest\x12 \n\x07metrics\x18\x01 \x03(\x0b\x32\x0f.metrics.Metric\"/\n\x15SubmitMetricsResponse\x12\x16\n\x0e\x61\x63\x63\x65pted_count\x18\x01 \x01(\r\"\x90\x01\n\x11GetMetricsRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x61gent_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\r\n\x05limit\x18\x03 \x01(\r\x12\x1a\n\rsince_unix_ms\x18\x04 \x01(\x03H\x02\x88\x01\x01\x42\x07\n\x05_nameB\x0b\n\t_agent_idB\x10\n\x0e_since_unix_ms\"6\n\x12GetMetricsResponse\x12 \n\x07metrics\x18\x01 \x03(\x0b\x32\x0f.metrics.Metric2\xa7\x01\n\x0eMetricsService\x12N\n\rSubmitMetrics\x12\x1d.metrics.SubmitMetricsRequest\x1a\x1e.metrics.SubmitMetricsResponse\x12\x45\n\nGetMetrics\x12\x1a.metrics.GetMetricsRequest\x1a\x1b.metrics.GetMetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics.metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC_LABELSENTRY']._loaded_options = None
  _globals['_METRIC_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_METRIC']._serialized_start=35
  _globals['_METRIC']._serialized_end=209
  _globals['_METRIC_LABELSENTRY']._serialized_start=164
  _globals['_METRIC_LABELSENTRY']._serialized_end=209
  _globals['_SUBMITMETRICSREQUEST']._serialized_start=211
  _globals['_SUBMITMETRICSREQUEST']._serialized_end=267
  _globals['_SUBMITMETRICSRESPONSE']._serialized_start=269
  _globals['_SUBMITMETRICSRESPONSE']._serialized_end=316
  _globals['_GETMETRICSREQUEST']._serialized_start=319
  _globals['_GETMETRICSREQUEST']._serialized_end=463
  _globals['_GETMETRICSRESPONSE']._serialized_start=465
  _globals['_GETMETRICSRESPONSE']._serialized_end=519
  _globals['_METRICSSERVICE']._serialized_start=522
  _globals['_METRICSSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
